"""add pending downgrade fields to subscriptions

Revision ID: 180321c5cf79
Revises: a063608d7e92
Create Date: 2026-07-27 06:43:09.316019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180321c5cf79'
down_revision: Union[str, Sequence[str], None] = 'a063608d7e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('pending_plan_name', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('pending_plan_effective_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'pending_plan_effective_at')
    op.drop_column('subscriptions', 'pending_plan_name')
    # ### end Alembic commands ###
