"""add api_key_id to usage_records

Revision ID: 57c267d157c9
Revises: 617c0496b439
Create Date: 2026-07-26 13:20:04.840448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c267d157c9'
down_revision: Union[str, Sequence[str], None] = '617c0496b439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_records', sa.Column('api_key_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_usage_records_api_key_id'), 'usage_records', ['api_key_id'], unique=False)
    op.create_foreign_key(None, 'usage_records', 'api_keys', ['api_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_records', type_='foreignkey')
    op.drop_index(op.f('ix_usage_records_api_key_id'), table_name='usage_records')
    op.drop_column('usage_records', 'api_key_id')
    # ### end Alembic commands ###
